### ISSUE TITLE
Only one object in a NLP entity?

### ISSUE THREAD

**Issue by yevhen-shulha** [SmartloopAI/smartloop-feedback#10]
It seems like the nlp object returns only one entity when there are two. 

I created a bot that tells the current currency exchange rate for the Ukrainian hryvnia. My objective is to teach it a simple calculation. If a user asks 'calculate 100 euro', the bot has to respond with the amount of Ukrainian hryvnia equivalent to 100 euro at the current exchange rate. And the same goes for the US dollar. 

So we have two entities: a number and a currency (either euro or dollar). 

I created the block doing just that and entered a dozen expressions like 'calculate $number $currency' and marked them "number" and "money" respectively to train the AI. 

Unfortunately, it doesn't work. When I debug the code it looks like that when I enter 'calculate 200 euro', the NLP recognizes only the type of currency, not the number.   

calculate 200 euro 
{"entities":[{"confidence":0.9151083377485706,"entity":"money","value":"euro","start":14,"end":18}],"intent":{"name":"calculate","confidence":0.9700719118118286}} 

It is still possible to get the number from context.args, but it would be great to have 2 (or more) entities in the nlp, e.g. 'money' and 'number'.

**Comment by mehfuzh** [comment]
Then entities should return an array of items, as it is shown up there, flagging this as a bug

**Comment by mehfuzh** [comment]
Hi Yeven,

Did you try this?

Let's say I have defined the following entities
<img width="650" alt="Screen Shot 2020-08-11 at 12 48 49 PM" src="https://user-images.githubusercontent.com/141204/89942245-111d4480-dbd1-11ea-999e-2a37e3bd73d1.png">


Next, I add the following using script block:


```
import Ext from 'bot-extension';
const __ = Ext.default;

exports.handler = (context, done) => {
    console.log(context.nlp);
    done(__.text("Hello world"));
};

```

When I type "chat with an agent", it returns the following:


```
{"entities":[{"confidence":0.7183981500195172,"entity":"ordinal","value":"chat","start":0,"end":4},{"confidence":0.8112104678884197,"entity":"human","value":"agent","start":13,"end":18}],"intent":{"name":"agent","confidence":0.9451653957366943}}

```
