### ISSUE TITLE
Config variables are hidden on Viber

### ISSUE THREAD

**Issue by vxzry** [SmartloopAI/smartloop-feedback#11]
**Describe the bug**

When creating a Viber bot, we can't see the Configurations on the Configure tab. 

**Which platform(s) does the issue occur on**

Viber

**Does this issue happen every time?**

Yes

**To Reproduce**

Create a Viber bot, go to Configure.

**Expected behavior**
Configurations must be present on the Configure tab.

**Additional context**

See screenshot below.
![image](https://user-images.githubusercontent.com/20976789/84782683-e96b8f00-b01a-11ea-9d54-37aaef2c4061.png)
Can we edit config variables thru script blocks while this isn't available?

**Comment by mehfuzh** [comment]
Thanks for reporting this. This is added in the latest update.
