### ISSUE TITLE
RichMedia preview is not available.

### ISSUE THREAD

**Issue by Erwin-Kation** [SmartloopAI/smartloop-feedback#13]
**Describe the bug**
When showing cards with images in viber on IOS, users are getting the message RichMedia preview is not available..

**Which platform(s) does the issue occur on**
Viber

**Does this issue happen every time?**
No

**To Reproduce**
Images from Card are retrieved from an API call

**Expected behavior**
Display Cards with Images

**Additional context**

**Comment by mehfuzh** [comment]
This is only in the live chat section, Users do see it  in the Viber bot

**Comment by mehfuzh** [comment]
Duplicate of #14
