### ISSUE TITLE
Staff account

### ISSUE THREAD

**Issue by win-tion** [SmartloopAI/smartloop-feedback#15]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to grant other people access to my account so that they can maintain the bot and monitor the campaigns without having to share my account

**Describe alternatives you've considered**
Share my account

**Additional context**

**Comment by mehfuzh** [comment]
@Erwin-Kation  I saw that you have invited me to your project, if this works then I will close it.

**Comment by Erwin-Kation** [comment]
It only works for people with smartloop.ai email accout. It doesn't work for any other email domains even the public domains.

Getting error: Please invite a user with a valid account.

Kind regards,
Erwin

________________________________

**Comment by mehfuzh** [comment]
Thanks, I will add it in the pipeline

**Comment by mehfuzh** [comment]
It is now possible to invite people who do not have smartloop account
