### ISSUE TITLE
Send email to {{email}}

### ISSUE THREAD

**Issue by mdembow** [SmartloopAI/smartloop-feedback#17]
**Is your feature request related to a problem? Please describe.**
Currently it is not possible to send an email to an address that is stored in a variable, for example, {{email}}.

**Describe the solution you'd like**
In the email plug-in, I would like to be able to send email to {{email}}.

**Additional context**
Please see this screenshot showing what I would like to do:
(https://user-images.githubusercontent.com/11546696/85591541-3bec1300-b5fa-11ea-9e09-fb7e2d0d65e1.jpg)

**Comment by mehfuzh** [comment]
This is now resolved. Let me know if you are having issues.

**Comment by mdembow** [comment]
Thank you. I just submitted a new request to allow custom sender names in
email.
