### ISSUE TITLE
Custom Sender for Emails

### ISSUE THREAD

**Issue by mdembow** [SmartloopAI/smartloop-feedback#20]
When sending emails, we would like to be able to specify a custom sender name. For example, please see the attached screenshot. Notice that the sender name is "Smartloop". When my company sends emails to our customers, we would like to replace "Smartloop" with our company name so that our customers can see that the email is from us. (Our customers don't know who Smartloop is.) Of course the true email sender will still be no-reply@smartloop.ai, but we want to be able to give a custom name.

<img width="1225" alt="Screenshot" src="https://user-images.githubusercontent.com/11546696/86290230-f43d2c80-bba1-11ea-9e06-fb09c52d0c60.png">

**Comment by mehfuzh** [comment]
I thinking that it should be tied to your company name from the settings, in this way, this is verified properly or there might scenario where your company name different in for each client?

**Comment by mdembow** [comment]
We work on behalf of multiple companies, so it would be best if we could
specify a unique sender name for each email block.

**Comment by mdembow** [comment]
Also, our project would be much easier if PATCH requests were possible. (As
you know, I have already submitted a request for PATCH requests.)

**Comment by mehfuzh** [comment]
Hello,

Please check out the latest update:

The from will be your "Bot Name", meaning whatever you set as bot name, it will be in the from. 

In addition, we have started to add the following line in notification emails to avoid spams


This is a system generated message and please do not reply to his email. If this is an error please reach out to: email@email.com
--


This is your owner / user email which you can update from the settings.


Finally, we have removed any Smartloop branding from notification emails.


Hope this helps

**Comment by mdembow** [comment]
Thank you, Mehfuz!
