### ISSUE TITLE
Maintain bots thru code

### ISSUE THREAD

**Issue by vxzry** [SmartloopAI/smartloop-feedback#22]
**Is your feature request related to a problem? Please describe.**
 
We have multiple bots and it's hard to maintain each of them, especially when we have to apply changes to our bots. 

**Describe the solution you'd like**

Is it possible to maintain a code version of the bots, maybe a json file, and apply it to different bots? Do you have a tool for this?

**Comment by mehfuzh** [comment]
We don't maintain a code version of the bot but we are adding support for cloning between multiple platforms that will make it easier

**Comment by vxzry** [comment]
Suppose that we have a **dev bot** and a **live bot**, when applying changes to the live bot it's easier if we could just copy the dev bot and make it the live bot, but then, the live bot has all the data so we can't transfer it to another bot. 
Do you have any suggestions for this scenario?

**Comment by mehfuzh** [comment]
We will introduce a draft mode that will let you do just that @kazimanzurrashid  @Fatme @vaskess

**Comment by kdubious** [comment]
Sounds useful. Also would be good to be able to move "responses" from one block to another. Or to copy / paste "responses" to use them multiple time in a flow.

**Comment by mehfuzh** [comment]
@kdubious  you can clone a block

**Comment by kdubious** [comment]
@mehfuzh I have seen that feature. But I needed (wanted) to be able to "clone" responses. For example, in a typical waterfall type dialog, one would aske a few questions in a row:
1. On a scale of 1 to 5, how happy are you with customer service? **< "Text Response"**
[1][2][3][4][5] **< "5 Quick Replies"**
2. On a scale of 1 to 5, how likely are you to refer us to a friend?
[1][2][3][4][5]

It's slow to build these out one at a time.

**Comment by mehfuzh** [comment]
This is cool. 

However, you do the following:
 
*Block 1*. On a scale of 1 to 5, how happy are you with customer service? < "Text Response"
[1][2][3][4][5] < "5 Quick Replies"

Jump to *Block2*

Clone:

Block 2:
Change to:

On a scale of 1 to 5, how likely are you to refer us to a friend?
[1][2][3][4][5]

But I get what you saying, I would suggest to open a feature request.
