### ISSUE TITLE
Reset a User Session

### ISSUE THREAD

**Issue by mdembow** [SmartloopAI/smartloop-feedback#24]
Our users may come back to our bot multiple times, and each time they come back, we want the "memory" of the previous visit to be erased. In other words, each new visit should be as if the user cleared their browser history. How can we achieve this behavior?

**Comment by mehfuzh** [comment]
The bot has a session with a sliding window of 30 minutes. However, you can forcefully clear  session using the following script:

```

import Ext from 'bot-extension';
const __ = Ext.default;

exports.handler = (context, done) => {
    context.vars.unset("session");
    done();
};

```
