### ISSUE TITLE
Add Block Id on outgoing webhooks

### ISSUE THREAD

**Issue by vxzry** [SmartloopAI/smartloop-feedback#27]
**Is your feature request related to a problem? Please describe.**
 
Is it possible to add the block Id on your outgoing webhooks? It would be easier to create logs if we know which block it came from.

**Comment by mehfuzh** [comment]
Which plans is it Facebook / Viber / Web ?

**Comment by vxzry** [comment]
Both for Facebook and Viber.

**Comment by mehfuzh** [comment]
Right now it sends out "intentId" which basically points to a block Id. However, this will be deprecated and we will also add blockId as we separate out the two.

**Comment by vxzry** [comment]
Hi, thanks for the update! 
I've got another question. Will the Viber webhook send out the `userId` on future releases?  On Facebook, there's `payload.recipient.id`, but on Viber it just returns `payload: true`

**Comment by mehfuzh** [comment]
I am logging this issue and will check along with the previous one
