### ISSUE TITLE
Entities Not Working On Squarespace Chatbot

### ISSUE THREAD

**Issue by mdembow** [SmartloopAI/smartloop-feedback#28]
When I deploy my smartloop bot on a squarespace website, the entities feature fails. However, when I run the same bot as a preview inside smartloop, the entities feature works fine. What might be going wrong?

**Comment by mehfuzh** [comment]
What is the specific issue, do you have steps to reproduce it?

**Comment by mdembow** [comment]
The first screenshot below shows what I am trying to do. My entity is
called "human". There are two possible values for this entity: "human" and
"help". In other words, {{human.value}} == "human" OR {{human.value}} ==
"help". I am trying to simply print the value of the entity with
console.log when the user types a response (the second screenshot shows
this). The third screenshot shows what happens when I run the bot as a
preview within Smartloop. As you can see, the value of the entity prints
correctly. The fourth screenshot shows what happens when I run the bot on
Squarespace. As you can see, the entity is not getting properly assigned.

**Comment by mdembow** [comment]
Correction: I am not using console.log to print, I am using a text block,
as you can see in the second screenshot.

**Comment by mehfuzh** [comment]
I don't see a screenshot what is your bot and can you send an email to support

**Comment by mehfuzh** [comment]
I got your issue and I will check now.

**Comment by mehfuzh** [comment]
Please check now, this should be fixed now. You should see something like:

````
{"entities":[{"confidence":0.7357586771824414,"entity":"human","value":"help","start":7,"end":11}],"intent":{"name":"human","confidence":0.9651098251342773}}
````
