### ISSUE TITLE
Is eval prohibited? How do I calculate?

### ISSUE THREAD

**Issue by yevhen-shulha** [SmartloopAI/smartloop-feedback#30]
My bot deals with currency exchange, so it would have been useful If she could do simple math for users without switching to an external calculator. But 'eval' seems to be prohibited for security reasons. Is there another function I can use to make my bot calculate from user input?

**Comment by mehfuzh** [comment]
Hi Yeven,
You can. use basic functions to do this, using regular expression.  We will be moving script out as a module and reference it from the builder, then you can use the full developer SDK to do such things


Hope this helps.

**Comment by yevhen-shulha** [comment]
Did you mean, the best way to do that is to extract numbers and the sign from context.args using regular expressions and then do the math?

**Comment by mehfuzh** [comment]
That will be the best way for now.
