### ISSUE TITLE
Agency Account

### ISSUE THREAD

**Issue by kdubious** [SmartloopAI/smartloop-feedback#31]
**Is your feature request related to a problem? Please describe.**
 
No

**Describe the solution you'd like**

I'd like to have multiple client accounts under my top level account.

**Describe alternatives you've considered**

**Additional context**

**Comment by mehfuzh** [comment]
Hello-

It possible and it is not have to be an agency account, there are multiple agencies using the platform in this way. There is a sharing capability which you can use to share your bot with your team.

Hope this helps
