### ISSUE TITLE
Web Chat Bot hangs on first user input

### ISSUE THREAD

**Issue by shnizmuffin** [SmartloopAI/smartloop-feedback#33]
**Describe the bug**
When a user submits their first User Input, in both cases `{{name}}`, the chat fails to move forward.

**Which platform(s) does the issue occur on**
Web

**Does this issue happen every time?**
Yes, across two bots.

**To Reproduce**
Go [here](https://dev.experiencehealth.com/). Tell the chatbot your name.

**Expected behavior**
Chatbot should reply "Hi, `{{name}}`"

**Additional context**
This does not happen in the Dashboard Preview.

**Comment by kdubious** [comment]
Was just coming here to post this... my issue was setting {{email}}.

**Comment by shnizmuffin** [comment]
This issue seems to have resolved itself.
