### ISSUE TITLE
Flag for a Block to not allow Interruptions

### ISSUE THREAD

**Issue by kdubious** [SmartloopAI/smartloop-feedback#34]
**Is your feature request related to a problem? Please describe.**
 
Create a Block designed to gather several pieces of data. You ask a question. The user's answer is not an answer, it is a trigger phrase for another block. In this case, the User Input validation does not run, the other block runs.

**Describe the solution you'd like**

Would be nice if a Block could have a flag that lets it accept interruptions or not.

**Describe alternatives you've considered**

**Additional context**

**Comment by mehfuzh** [comment]
Are you setting up expression correctly?
