### ISSUE TITLE
Export contact list

### ISSUE THREAD

**Issue by kdubious** [SmartloopAI/smartloop-feedback#39]
**Is your feature request related to a problem? Please describe.**
 
Running an email campaign (Mailchimp, for example) against the list is difficult.

**Describe the solution you'd like**

**Describe alternatives you've considered**

Could post data to Mailchimp during data capture, but export is easy enough.

**Additional context**

**Comment by mehfuzh** [comment]
How about using with Zapier during data capture, do you want to export the data instead from Audience tab?

**Comment by kdubious** [comment]
From the audience tab. I imagine over time, this could be a big list. And where the data needs to go could change. So having to send data to a back end for each data edit isn't the best solution for some of the use cases I can think of. A button to export an HTML table to CSV is pretty simple.

**Comment by mehfuzh** [comment]
I have just released this, you should now able to export data from audience tab 

<img width="683" alt="Screen Shot 2020-11-07 at 12 41 33 AM" src="https://user-images.githubusercontent.com/141204/98436668-08ce8b80-2092-11eb-891e-78ef8adc3092.png">
