### ISSUE TITLE
[Facebook][Viber] Use variables on URL buttons

### ISSUE THREAD

**Issue by vxzry** [SmartloopAI/smartloop-feedback#4]
**Is your feature request related to a problem? Please describe.**
 
This is for Facebook and Viber. I can't use variables on URL type buttons. We need this because our URLs are dynamic and different for each user.

**Describe the solution you'd like**

Allow the use of variables on URL buttons.

**Describe alternatives you've considered**

I tried using Script blocks to create cards with URL buttons, it works but there's no option to redirect me into another block. 

**Additional context**

Using the variable `{{{redirect_url}}}` results to this URL
`https://connect.smartloop.ai/%7B%7B%7Bredirect_url%7D%7D%7D`
![image](https://user-images.githubusercontent.com/20976789/84570021-16bb0180-adbd-11ea-92d3-382ba5a77e46.png)

**Comment by vxzry** [comment]
Is it possible for you to add the `block` parameter on the `urlButton`? Like this
`urlButton(title, url, block)`
and for Viber:
`urlButton(title, url, block, buttonProperties)`

**Comment by mehfuzh** [comment]
Btw, we have added the support for variables in the URL button, please check and let me know.

**Comment by vxzry** [comment]
Hi, 
It's still not generating the url from the variable.

**Comment by mehfuzh** [comment]
How are you setting your variables? Using user attribute plugin or some other way? Where do you set this `redirect_url`?

**Comment by vxzry** [comment]
Using the script block

**Comment by vxzry** [comment]
I noticed that the URL works on the Preview pane but not on Messenger.

**Comment by mehfuzh** [comment]
Thanks for pointing that out, I will take a look at it today (stay tuned) but ideally, try using the "user attribute" plugin if possible.

**Comment by vxzry** [comment]
I'm not sure if the user attribute plugin is fit for the scenario, our links are generated from the script block and that's where we assign them to the `vars`.

**Comment by vxzry** [comment]
Will you also allow the use of unescaped variables for the URLs? 
![image](https://user-images.githubusercontent.com/20976789/85860260-12490c80-b7f1-11ea-8af8-5f8de42a510d.png)

**Comment by mehfuzh** [comment]
Not sure what you mean, you specify that it is a variable by  "{}" double braces syntax.

**Comment by mehfuzh** [comment]
which plugin is that?

**Comment by vxzry** [comment]
We use the triple brace for unescaped values, from the mustache template. 
![image](https://user-images.githubusercontent.com/20976789/85949933-270dd780-b98c-11ea-9108-b469d1d7b15b.png)

Using the double brace for the links would encode some of the characters.

![image](https://user-images.githubusercontent.com/20976789/85950124-7f91a480-b98d-11ea-8835-f467948c8b42.png)

![image](https://user-images.githubusercontent.com/20976789/85950118-73a5e280-b98d-11ea-8b2f-84ba33687217.png)

**Comment by mehfuzh** [comment]
Ideally, both escaped and unescaped values are supported.

**Comment by vxzry** [comment]
I couldn't use the triple brace due to the validation pattern on the url field.

![image](https://user-images.githubusercontent.com/20976789/86558161-29bf8c80-bf8b-11ea-871e-7000c8d2f55e.png)

**Comment by vxzry** [comment]
We're still unable to use variables on url fields.

**Comment by mehfuzh** [comment]
Hello,
I have noticed that you are trying to redirect to a block as well, I want to point out that you can actually to the following:


<img width="457" alt="Screen Shot 2020-07-22 at 11 20 18 PM" src="https://user-images.githubusercontent.com/141204/88257205-14787c80-cc72-11ea-9e72-8be8355c3fd8.png">


Let me take a look into the above issue

**Comment by mehfuzh** [comment]
Please check now. 

If you are using a Facebook bot (based on screenshot above), then in addition to using variables you would also need to whitelist the domain if you check "messenger extension" as there is no way to infer an URL from script/variable.  Please also note that Facebook only supports `https`. Apart from this, you can do the following:

* {{url}} - escaped
* {{{url}}} - unescaped

**Comment by vxzry** [comment]
Hi, thanks for the update. Is there anything else I should look into? I'm still getting this url when using variables. 
`https://connect.smartloop.ai/%7B%7B%7Burl%7D%7D%7D`

**Comment by mehfuzh** [comment]
That's the internal URL that redirects to you a block what your bot and what are you trying to do?

**Comment by vxzry** [comment]
Here's what we're doing:

### Smartloop

On the script block, we set the url variable
Then create a button template with a URL button
![image](https://user-images.githubusercontent.com/20976789/89246904-b5861080-d63e-11ea-9bd9-91b69478614d.png)

Set the url variable to the button
![image](https://user-images.githubusercontent.com/20976789/89246922-bf0f7880-d63e-11ea-8626-205f7d7363da.png)

### Messenger

And then on messenger, here's the result.
![image](https://user-images.githubusercontent.com/20976789/89247006-ecf4bd00-d63e-11ea-9b0e-cfc8a171c6ba.png)

Upon clicking the button, we get an Invalid link error
![image](https://user-images.githubusercontent.com/20976789/89246729-5f18d200-d63e-11ea-8998-f84d33b52fda.png)

On mobile, here's what we're getting 
![image](https://user-images.githubusercontent.com/20976789/89247295-9f2c8480-d63f-11ea-9f7f-518aa24eeaea.png)

**Comment by vxzry** [comment]
Just tried yesterday and variable urls are now working! Thanks!

**Comment by mehfuzh** [comment]
Glad that it is working for you

**Comment by vxzry** [comment]
Hi, just noticed that it gives an invalid link when filling up the "block name" field. It works without the block name. 
![image](https://user-images.githubusercontent.com/20976789/91374267-6cdf0300-e84a-11ea-9ed8-9378813419e7.png)
![image](https://user-images.githubusercontent.com/20976789/91374297-7cf6e280-e84a-11ea-8b21-47b6cc12f10c.png)

**Comment by mehfuzh** [comment]
I don't see such issue, make sure that you have added space in the {{{{url}}}

**Comment by vxzry** [comment]
Yes, our links are already whitelisted and working without the block name. What do you mean by "added space in the {{{url}}}", maybe I should check on that.

**Comment by mehfuzh** [comment]
what is your bot Id? Let me check on that

**Comment by vxzry** [comment]
Here's our bot id: 418934d1323a5c8169abb8a18a6d61fe
Here's the block: orders > orderconfirmationweb (80133741e69511eab452bbcf5d9530a9)

**Comment by mehfuzh** [comment]
Please check it now and let know if you still the "invalid link"

**Comment by vxzry** [comment]
Hi, thanks for your help! It worked! :D
