### ISSUE TITLE
All Attributes

### ISSUE THREAD

**Issue by kdubious** [SmartloopAI/smartloop-feedback#40]
**Is your feature request related to a problem? Please describe.**
 

**Describe the solution you'd like**

Would be nice to have a way to print "All" attributes for a session. For example, if you are sending a notification email, would be nice to know all the values set for a user to email to the admin.

**Describe alternatives you've considered**

**Additional context**

**Comment by mehfuzh** [comment]
You can try the following:

```

import Ext from 'bot-extension';
const __ = Ext.default;

exports.handler = (context, done) => {
    console.log(context.vars);
    done();
};
```

**Comment by kdubious** [comment]
@mehfuzh I don't see it logging to the console, though. Does it not work with Facebook?
