### ISSUE TITLE
Newline in variable in Email

### ISSUE THREAD

**Issue by kdubious** [SmartloopAI/smartloop-feedback#42]
**Describe the bug**

I tried using `<br>` and also `\r\n` but neither create a new line in a variable in the email tool.

**Which platform(s) does the issue occur on**

**Does this issue happen every time?**

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by mehfuzh** [comment]
you should be able to just hit enter in the plugin, since its a textarea? what am I missing here?

**Comment by kdubious** [comment]
@mehfuzh The body of the email is being built by a variable. I'm using a script to grab all attributes active for the visitor, and build them into a string. Whether I use "<br>" or "\n" does not work to create a new line in the email body.

**Comment by mehfuzh** [comment]
@kdubious Thanks, I will check it out and keep you posted

**Comment by mehfuzh** [comment]
ok use {{{ body }}} (triple) instead of {{ body }} (double). This will tell the system not to encode the variable

**Comment by mehfuzh** [comment]
I am also in the process of adding a markdown editor, similar to one we are using here in github.

**Comment by kdubious** [comment]
@mehfuzh ok, sounds good. I'll give it a shot.
