### ISSUE TITLE
Disclaimer text in Send Email plugin

### ISSUE THREAD

**Issue by irina-welsh** [SmartloopAI/smartloop-feedback#43]
**Is your feature request related to a problem? Please describe.**

 
The Send Email plugin has a disclaimer: _PS - If you didn’t request this email, there’s nothing to worry about — you can safely ignore it._ When you see this disclaimer in the email, it distracts you from the main content of the email.

**Describe the solution you'd like**

Would it be possible to disable this disclaimer?

**Describe alternatives you've considered**

**Additional context**

**Comment by mehfuzh** [comment]
Hi Irina,

This is removed, good point!~
