### ISSUE TITLE
Send email fails to send {{email}}

### ISSUE THREAD

**Issue by irina-welsh** [SmartloopAI/smartloop-feedback#44]
**Describe the bug**

{{email}} does not show a value in the body of an email sent with Send Mail element

**Which platform(s) does the issue occur on**

Web

**Does this issue happen every time?**

Yes

**To Reproduce**

Created a UserInput element to gather {{email}}
Verified the value is set with a Text element
Use SendEmail element to send with body that includes {{email}}
{{email}} does not appear in the actual email that is sent

NOTE

Also tried setting a UserAttribute {{a}} to an email address "a@a.com"
Send Email element DOES show that value.

**Expected behavior**

**Additional context**

**Comment by mehfuzh** [comment]
The issue is resolved now, thanks for reporting it
