### ISSUE TITLE
context.vars.values vs context.vars.map

### ISSUE THREAD

**Issue by irina-welsh** [SmartloopAI/smartloop-feedback#45]
**Describe the bug**

In web chat, values are stored here: `context.vars.map` but in Facebook bots, they are here `context.vars.values`

**Which platform(s) does the issue occur on**

FB / Web

**Does this issue happen every time?**

Yes

**To Reproduce**

run `console.log(context.vars);` in a web versus a facebook bot

**Expected behavior**
A consistent API across all platforms

**Additional context**

**Comment by mehfuzh** [comment]
HI Irinia,

You should not be using context.vars.map / values..


Rather the correct with to use the 

```
context.vars.get("key");
context.vars.set("key");

// this will unset the key.
context.vars.unset("key");

```

**Comment by kdubious** [comment]
@mehfuzh We need a way to loop over ALL context variables, not knowing what they are. In other words, we set things like "email" and "first name" and "product category preference", etc. We want to be able to build a string variable that finds all the variables with values so we can email it out.
