### ISSUE TITLE
Unable to save WEBHOOK URL

### ISSUE THREAD

**Issue by kdubious** [SmartloopAI/smartloop-feedback#46]
**Describe the bug**

Unable to save WEBHOOK URL
Leave the screen and come back, and the value is empty

**Which platform(s) does the issue occur on**

FB

**Does this issue happen every time?**

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by mehfuzh** [comment]
This is now fixed. Let me know if you are still facing this issue
