### ISSUE TITLE
Problem using URL variable to access API

### ISSUE THREAD

**Issue by maximdembow** [SmartloopAI/smartloop-feedback#51]
This problem is confusing because it was working properly before.

Our goal is to use a URL parameter to specify a row in a database. We are storing the URL parameter inside a variable called external_conversation_id. Here is the relevant code from our Squarespace website:
<img width="759" alt="Storing URL Parameter" src="https://user-images.githubusercontent.com/74160795/98488945-ba7bd280-21e0-11eb-8039-fa54370a98a6.png">

Within Smartloop, the following code allows us to print the external_conversation_id:
<img width="705" alt="Printing external_conversation_id" src="https://user-images.githubusercontent.com/74160795/98488997-0464b880-21e1-11eb-89e5-378f1d68fee5.png">

And here is the print-out:
<img width="340" alt="Printout of external_conversation_id" src="https://user-images.githubusercontent.com/74160795/98489088-54437f80-21e1-11eb-9eac-dbac101e22a0.png">

We would like to use the variable external_conversation_id in a JSON request. Before showing what goes wrong when we try to do that, observe that our JSON request works fine when we hard-code the value. Here we are using the hard-coded value to print the name of the user associated with that value, "brandon":
<img width="627" alt="hard-coded value" src="https://user-images.githubusercontent.com/74160795/98489480-00399a80-21e3-11eb-945b-6bc24f8654a3.png">

And here is the print-out:
<img width="332" alt="print-out of name" src="https://user-images.githubusercontent.com/74160795/98489497-0fb8e380-21e3-11eb-9402-9208b12e0369.png">

However, when we use the variable name, external_conversation_id, our JSON request fails:
<img width="705" alt="using the variable name" src="https://user-images.githubusercontent.com/74160795/98489547-4ee73480-21e3-11eb-94bd-86c9005ce7cc.png">

Here is the failed print attempt:
<img width="344" alt="failed JSON request" src="https://user-images.githubusercontent.com/74160795/98489585-7b02b580-21e3-11eb-99b5-3dcbd33ea118.png">

I thought there might be a timing issue, so I added a 5-second delay to allow more time for the URL parameter to load. However, that did not solve the issue. Again, I wish to emphasize that this was working correctly before now. 

What might be going wrong?

**Comment by mehfuzh** [comment]
What is Test[0] here, where are you setting it?

**Comment by maximdembow** [comment]
The variable "test" is being assigned the value of "outreach_convo", which is a database row returned via GET request. This assignment takes place on line 8 in the first two screenshots, and on line 10 in the third screenshot. The purpose of the index [0] in test[0] (I believe) is to specify the first JSON object returned from the GET request. In this case, the GET request only finds a single match, but it still seems to be necessary to include the index [0].

**Comment by maximdembow** [comment]
It is definitely a timing issue. Later on in the program the GET request works fine with the {{external_conversation_id}} syntax. The question is how to make it work at the beginning?

**Comment by mehfuzh** [comment]
Hi Maxim,

I just tried your script:



and looks like it is passing the variable correctly.

```
<html>
    <body>
        <script>
            // Pase your Script here
        </script>
        
        <script>
            function getUrlVars(){
                var vars = {};
                var parts = window.location.href.replace(/[?&]+([^=&]+)=([^&]*)/gi, function(m, key, value){
                    vars[key] = value;
                });

                return vars;
            }

            (function(window) {

            const { id ='', outreach_convo } = getUrlVars();

            window.addEventListener('load', function(){
                // console.log('window loaded');
                const { webchat } = window;

                console.log(outreach_convo);

                const userId = webchat.getUserId();

                webchat.setUser({
                    custom : {
                        external_conversation_id: id,
                        smartloop_conversation_id: userId
                    }
                })
            });

            })(window);

        </script>
    </body>

</html>

```

The issue I see is with out `outreach_convo` as the following request returning `[]` for any value


<img width="571" alt="Screen Shot 2020-11-18 at 7 10 26 PM" src="https://user-images.githubusercontent.com/141204/99616314-dd249d00-29d1-11eb-89c1-2c774e6990ea.png">

**Comment by maximdembow** [comment]
Adding the following code just prior to the GET request solved the issue:

    let external_conversation_id = context.vars.get(“external_conversation_id”);
    context.vars.set(“external_conversation_id”, external_conversation_id);

It seems that it is necessary to declare the URL variable globally before it can be used in a GET request.

**Comment by mehfuzh** [comment]
That is odd but I will cehck
