### ISSUE TITLE
POST Request Failing on Final Item in JSON Array

### ISSUE THREAD

**Issue by maximdembow** [SmartloopAI/smartloop-feedback#52]
The following POST request is working correctly for the first three items, but failing on the final item:

<img width="527" alt="Screen Shot 2020-11-24 at 2 29 25 PM" src="https://user-images.githubusercontent.com/74160795/100158733-7edc3c00-2e61-11eb-8f5a-86296fc2c1f7.png">

Notice that the fourth and final item, email, is not being added to our database:

<img width="652" alt="Screen Shot 2020-11-24 at 2 30 49 PM" src="https://user-images.githubusercontent.com/74160795/100158884-b9de6f80-2e61-11eb-8acb-98852b5621cc.png">

The code responsible for declaring and assigning the "email" variable is located in the block directly preceding the failed POST request. Here is that code:

<img width="462" alt="Screen Shot 2020-11-24 at 2 36 54 PM" src="https://user-images.githubusercontent.com/74160795/100159393-8b14c900-2e62-11eb-9c39-b42f38ec6710.png">

In the code above, notice the print statement. Here is the result from that print statement, which shows that the "email" variable exists and has been assigned:

<img width="345" alt="Screen Shot 2020-11-24 at 2 39 35 PM" src="https://user-images.githubusercontent.com/74160795/100159605-e777e880-2e62-11eb-9a2a-125f4a06b385.png">

The API appears to be working correctly -- I have tested the API with Postman. The problem seems to be located somewhere else. Any help would be greatly appreciated.

**Comment by mehfuzh** [comment]
Where are you capturing the email?

**Comment by mehfuzh** [comment]
I am saying this because email is captured as user attribute when you set it from outside for web bot. Try `user.email` instead.

https://docs.smartloop.ai/user-attributes.html

**Comment by maximdembow** [comment]
I don’t quite understand. Are you saying “email” is a reserved name? We
should not use the variable name “email” within the program?

**Comment by maximdembow** [comment]
We have a database column called “email”. That is where we are capturing
the email variable. (Please also see my question in the previous email.)

**Comment by mehfuzh** [comment]
Please try to use ``{{user.email}}` from the builder that will contain your email value, when you set email, it is set as ``{{user.email}}`
