### ISSUE TITLE
How do I get data from an html page?

### ISSUE THREAD

**Issue by yevhen-shulha** [SmartloopAI/smartloop-feedback#53]
I would like to scrap a few numbers from a webpage directly (I'm now doing it via a Google spreadsheet, but would like to skip an extra layer). 

Is it possible to do it in Smartloop? I know there are limitations to modules a user can call, and those I tried didn't work. 

Thanks!

**Comment by mehfuzh** [comment]
HI Yevhen,

You can use the request module to do:
https://docs.smartloop.ai/developer-features.html#request


Hope this helps

**Comment by yevhen-shulha** [comment]
Sure! Thank you!!!
