### ISSUE TITLE
Persistent menu not working

### ISSUE THREAD

**Issue by vxzry** [SmartloopAI/smartloop-feedback#54]
**Describe the bug**

Upon clicking an item on the persistent menu, it registers as a user input instead of a postback message which should redirect a user to a block.

**Which platform(s) does the issue occur on**

Facebook

**Does this issue happen every time?**

Yes

**To Reproduce**

Create a Persistent Menu, select Block, then choose the block from the options.

**Expected behavior**

Redirect the user to the block specified.

**Additional context**

**Comment by mehfuzh** [comment]
Do you have a bot Id?

**Comment by vxzry** [comment]
I'm not sure when it started but it occurs to all our Facebook bots, please check this one: fa4e21e62b2c660faff9f7715ff8c23e

**Comment by mehfuzh** [comment]
I tried the bot and don't see any issue there, apart from the fact you have a big script running under that menu option that is slowing the response down

**Comment by mehfuzh** [comment]
Closing the issue, feel free to re-open if you are still having issues

**Comment by vxzry** [comment]
Hi, we've noticed that it only happens on the web version of messenger, it works on the app.

**Comment by mehfuzh** [comment]
can you seme a link to your web version of the messenger app vis support so that I can test?
