### ISSUE TITLE
Current Page URL in Live Chat

### ISSUE THREAD

**Issue by maybevaibhav** [SmartloopAI/smartloop-feedback#58]
Hello,

Out company has lead gen pages for different types of services.

When a user starts a live chat, we don't know which service he's interested in as we can't see his current page.

Any chance you can include current page in the "User attributes" section?

**Comment by mehfuzh** [comment]
You can add it using custom attributes and set it on page load, as shown here:

https://docs.smartloop.ai/channel.html#sending-user-attributes

**Comment by maybevaibhav** [comment]
Thank you.

The person who’ll be using this are from the marketing team. We don’t know coding.

Is there any simple way to implement this feature?

I’d also like to see the IP address of the website visitor.

-Vaibhav

From: Mehfuz Hossain ***@***.***>
Date: Monday, 22 March 2021 at 23:55
To: SmartloopAI/smartloop-feedback ***@***.***>
Cc: maybevaibhav ***@***.***>, Author ***@***.***>
Subject: Re: [SmartloopAI/smartloop-feedback] Current Page URL in Live Chat (#58)

You can add it using custom attributes and set it on page load, as shown here:

https://docs.smartloop.ai/channel.html#sending-user-attributes

**Comment by mehfuzh** [comment]
That's fine, when you install the bot on a page, you can send those extra parameters as mentioned in the link, but soon we will also push it out to the live chat user profile. Ideally, you should create a separate bot for each website (not one bot for all websites), in this way you can separate the conversation
