### ISSUE TITLE
Disable auto save and implement manual save

### ISSUE THREAD

**Issue by maybevaibhav** [SmartloopAI/smartloop-feedback#59]
Hello,

Autosaving and publishing it to live without the user's consent is very risque.

Yesterday, I was testing and changed the greeting text to some random text. 

I'm new to Smartloop and didn't know that Smartloop autosaved it. 

One of our potential customers informed us that they're seeing some random characters, and it was very embarrassing for us.

This should be the workflow. 

I write or change something > Smartlopp autosaves them but keep them in a draft > I manually publish those changes to the live site.

**Comment by mehfuzh** [comment]
Manual save, is very old school, think about medium and similar products, no one uses manual save anymore. Ideally, the steps should be:
1. Clone the bot, make changes there then publish it to live.

Moving forward, we are going to implement, draft vs publish that will solve the issue.

**Comment by mehfuzh** [comment]
Moving to backlog
