### ISSUE TITLE
Show country of the user

### ISSUE THREAD

**Issue by maybevaibhav** [SmartloopAI/smartloop-feedback#60]
Hello,

We serve only US and UK citizens but our site gets tons of traffic from other countries. 

They also use the form. 

In our web form, we use a functionality where the web form captures the IP, uses free APIs to match the IP with the location, and send the data along with the web form fields (like names, email, requirements, etc.).

We filter the data based on the location.

We want something like this for our bot also.

**Comment by mehfuzh** [comment]
You can do this easily by some additional script on your page, please check below:

```
<script>
    window.addEventListener('load', function () {
        const userId = webchat.getUserId();

        webchat.setUser({
            first_name: 'John',
            last_name: 'Doe',
            country : 'US',
            email: 'john@smartloop.ai',
            custom: {
                external_ip: "172.16.0.1"
            }
        });
    });
</script>
```

**Comment by maybevaibhav** [comment]
So, I need to add this code to my website. And what custom code shall I add to the bot?

Could you please provide a step-by-step guide? I'm afraid that I am not a technical person.
