### ISSUE TITLE
Guest user messages not visible on Live Chat

### ISSUE THREAD

**Issue by vxzry** [SmartloopAI/smartloop-feedback#62]
**Describe the bug**

We're using the Customer Chat Plugin to use the bot on a website, messages from guest users are not visible on the live chat.

**Which platform(s) does the issue occur on**

Facebook 

**Does this issue happen every time?**

We were able to see guest user messages before.

**To Reproduce**

Copy the code for the Customer Chat Plugin and use on your website. Send a message as Guest. 

**Expected behavior**
Make guest messages visible on the Live chat.

**Additional context**

**Comment by mehfuzh** [comment]
Do you have more information on this, like anywhere I can test this?

**Comment by vxzry** [comment]
If you have a local html file, add the Customer Chat plugin provided on Smartloop Config.
Then use ngrok to make your local website available publicly, add the ngrok link to the whitelist.
Then send a message from the website using the chat plugin as guest. 

Guest messages aren't reflected on the live chat messages
