### ISSUE TITLE
How to use "Send email" to email the uploaded file

### ISSUE THREAD

**Issue by maybevaibhav** [SmartloopAI/smartloop-feedback#63]
Hello,

I use a pro account.

My customer attaches the files in 70% of the conversations. But, I'm having a hard time attaching that file to the email.

My team has to go to Smartloop to download the file. 

How do I send files in the email like other things like name and email?

PS I'm not a technical person. So, could you reply in a non-tech language?

**Comment by mehfuzh** [comment]
What do you mean by attaching a file to the email? Can you create a support ticket? Are you trying to attach a file from an email client or from smartloop?

**Comment by mehfuzh** [comment]
You can send image via email using 

```
{{image.0.url}}
```
