### ISSUE TITLE
The bot stopped responding to cyrillic commands

### ISSUE THREAD

**Issue by yevhen-shulha** [SmartloopAI/smartloop-feedback#64]
**Describe the bug**
My bot, Galya, is a currency-exchange bot that speaks mostly Ukrainian (Cyrillic alphabet), with a few commands available in Latin. Since two or three days ago, she stopped recognizing commands in Cyrillic, while the Latin commands are still available. Tried to retrain, didn't help. 

**Which platform(s) does the issue occur on**
Viber

**Does this issue happen every time?**
Yes

**To Reproduce**
Ask "Курс" or "Долар"

**Expected behavior**
To respond with an exchange rate, not a long explanation.

**Additional context**
the commands in Latin, like USD or 'euro' are processed correctly

**Comment by mehfuzh** [comment]
I have made some updates, can you try now? and do you have the bot Id, you can email me, in the support?

**Comment by mehfuzh** [comment]
Let me know if this is still the issue

**Comment by yevhen-shulha** [comment]
> Let me know if this is still the issue

No, everything is fine now, thank you!
