### ISSUE TITLE
Malfunction when sending multiline text via JSON API

### ISSUE THREAD

**Issue by tinegocios** [SmartloopAI/smartloop-feedback#65]
**Describe the bug**

When Smartloop is integrated into a Facebook fanpage, there is the possibility that the fan page visitor can write a response in multiline mode with the ENTER character (chr 13), for example:

Smartloop via FB: Hello, what is your address?
Visitor in FB Page: Hello (break line)
I live in Mexico (break line)
In Cancun

This is possible from the web browser or from the facebook messenger app when the user writes one or more line breaks within their response

This information can be stored as a user attribute, for example: userPlace

Later, if an API call is integrated and this data is sent as an attribute of that call, this will cause an error: for example

JSON API
Type: POST
URL: website.com/endpoint
body: {userPlace: "{{userPlace}}"}

Then, the value stored in userPlace will cause the generated JSON to be wrong when replacing userPlace with the stored value, since it will have the line breaks without being formatted for JSON, producing:

{userPlace: "Hello
I live in mexico
In Cancun "}

When should it produce:

{userPlace: "Hello\nI live in Mexico\nIn Cancun"}

This error currently generates the following message:

"Unexpected token in JSON at position XX"

Where XX corresponds to the first occurrence of the line break in the user attribute.

This error could be easily fixed by transforming all line breaks in the format for json: "\n"

**Which platform(s) does the issue occur on**

Facebook Messenger App / Facebook in Web Browser

**Does this issue happen every time?**

Yes

**To Reproduce**

Steep 1: Build a Smartloop flow like the following:

A.- Text -> Hello, what is your address?
B.- User input -> type: Text / Attribute: {{userPlace}} / Validation: None
C.- JSON API -> method: POST / url: website.com/endpoint / body: {userPlace: "{{userPlace}}"}

Steep 2: Then train the model and connect this with a facebook fanpage

Steep 3: As visitor, in facebook messenger or facebook via web browser, start the conversation and send any text with multiline as a single response in the userPlace question.

Steep 4: Smartloop going to response with "Unexpected token in JSON at position XX"

**Expected behavior**

The JSON must be like this

{userPlace: "Hello\nI live in Mexico\nIn Cancun"}

not like this

{userPlace: "Hello
I live in mexico
In Cancun "}

**Additional context**

There is a possibility that this error can also be presented with the use of other special characters in json, that should also be tested, for example if the response contains:
[
]
{
}
"
'
\
,
(tabulator)

**Comment by tinegocios** [comment]
A temporary workaround for this problem is to insert a pre-code block to the JSON API block.

Line breaks are replaced in this block and the error is avoided.

**Comment by mehfuzh** [comment]
Thanks for reporting this

**Comment by mehfuzh** [comment]
The error is correct, you can not have \n lines in a JSON request, ideally, you can use script block to remove "\n", we will check this behavior from our end
