### ISSUE TITLE
Script execution timeout

### ISSUE THREAD

**Issue by yevhen-shulha** [SmartloopAI/smartloop-feedback#66]
My bot tracks information on a website, but in an indirect way: a Google Sheet makes IMPORTXML request every minute, and the bot reads it via a JSON Query: 
https://sheets.googleapis.com/v4/spreadsheets/{{config.sheet}}/values/%D0%9A%D1%83%D1%80%D1%81?key={{config.key}}

The script is as simple as this:

import Ext from "bot-extension";
const __ = Ext.default;

exports.handler = (context, done) => {
    var aaa = context.vars.get('result');
    var eur_opt = aaa.values[1][1];
    var dol_opt = aaa.values[0][1];
    done(__.text('Зараз у Липинці оптимальний курс обміну долара '+dol_opt+' грн. Євро — '+eur_opt+' грн.'));
           };

**Describe the bug**
All too often (maybe half of the time), the bot responds with a "script execution timeout" message followed by a structurally correct response but with outdated results (say from 1-2 hours ago, stored probably somewhere in the cache).  

**Which platform(s) does the issue occur on**
Viber, but actually in the test web-environment as well. 

**Does this issue happen every time?**
No

**To Reproduce**
ask any question

Is there a bug in my code? 
Does Google Sheet cause that? Is there a way to wait longer for the Google Sheet answer?
Anything else to resolve the issue?

Thanks!

**Comment by mehfuzh** [comment]
closing this issue due to inactivtivty
