### ISSUE TITLE
Reply buttons from script block returns values prefixed with 'reply-'

### ISSUE THREAD

**Issue by vxzry** [SmartloopAI/smartloop-feedback#9]
**Describe the bug**

Just yesterday, all the reply buttons started giving out values with the 'reply-' prefix, we had to remove them from all our buttons. 

**Which platform(s) does the issue occur on**

Viber

**Does this issue happen every time?**

Yes, starting yesterday.

**To Reproduce**

Create a reply button thru the script block and add a user input block to get the value. 

**Expected behavior**
Reply button must not have a 'reply-' prefix just like before.  Unless you had a reason to do this I guess? Then at least tell us to expect this behavior from the reply button when you update.

**Additional context**

**Comment by mehfuzh** [comment]
Thank you for reporting this:

Ideally, you should not manually add "prefix" strings yourself to your Viber bot using a script. This makes it harder for backward compatibility and your bot for any future updates. I would recommend using `replyButton` instead moving forward:
```
import Ext from 'bot-extension';
const __ = Ext.default;
exports.handler = (context, done) => {
    done(__.buttonTemplate('Text', [
        __.replyButton('button1', 'about', {
        bgColor : '#e30c2e',
        fgColor : '#fff',
        row : 0,
        column : 0
        }),
        __.postbackButton('Button2', 'start', {
        bgColor : '#76c0d6',
        fgColor : '#fff',
        row : 0,
        column : 1
        })
    ]));
};

**Comment by mehfuzh** [comment]
Hello-,
I have checked your bot and you are correct about the issue, this should be resolved now. However, when you are using the script, please try to use the typed syntax to avoid any breaking changes.

Let me know if you have any questions

Hope this helps
Mehfuz

**Comment by vxzry** [comment]
Hi, 
Thanks for the update. 
What does it mean to have a row and column of 0?
